[package]
name = "change-git-log-author"
description = "Change git log author"
version = "0.1.0"
edition = "2021"
license = "MIT"

[[bin]]
name = "cgla"
path = "src/main.rs"

[dependencies]
clap = { version = "4.4.7", features = ["derive"] }
